version: 2.1

jobs:
  build:
    environment:
      X: x
    docker:
      - image: circleci/golang
      - image: circleci/golang
        entrypoint: env
    steps:
      - checkout
      - run:
          name: Echo
          command: echo OK
      - run:
          name: List
          command: ls
      - run:
          name: PWD
          command: pwd

workflows:
  version: 2
  build:
    jobs:
      - build
