version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang
        environment:
          HOGE: hoge
          X_HOGE: $X_HOGE
          foo:
    steps:
      - checkout
      - run:
          name: Echo
          command: echo OK
      - run:
          name: List
          command: ls
      - run:
          name: PWD
          command: pwd
      - run:
          name: env
          command: env

workflows:
  version: 2
  build:
    jobs:
      - build
