version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run:
          name: Echo
          command: echo OK
      - run:
          name: List
          command: ls
      - run:
          name: PWD
          command: pwd

workflows:
  version: 2
  build:
    jobs:
      - build
